### ISSUE TITLE
Request for Hackage Release

### ISSUE THREAD

**Issue by dynamicboid** [haskell-primitive/primitive-slice#1]
Hi Andrew, it seems this project was never uploaded to Hackage. I came across this when trying to use the `castagnoli` package in a Stack project and found myself unable to obtain this package as a required dependency even after adding it to my Stack `extra-deps`. Would it be possible for you to do a release of this package to Hackage?

**Comment by andrewthad** [comment]
Released! (Also, I cannot believe that you even found this. I haven't needed to use CRC32 in a long time.)

**Comment by dynamicboid** [comment]
Haha, thanks Andrew. You are awesome! I appreciate you taking the time to do this.
